version: 2.1
jobs:
  rescript-build-and-test:
    parameters:
      rescript-version: { type: string }
    docker:
      - image: cimg/node:16.6.0
    environment:
      CI: true
      NODE_ENV: test
      TC_RESCRIPT_VERSION: << parameters.rescript-version >>
    working_directory: ~/repo
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v1-rescript-dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v1-rescript-dependencies-{{ .Branch }}-
            - v1-rescript-dependencies-
      - run: make deps-rescript
      - run: make build-rescript
      - run: make test-rescript
      - run: make doc-rescript
      - run: make integration-test-rescript
      - save_cache:
          key: v1-rescript-dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/repo/node_modules

  native-build-and-test:
    parameters:
      ocaml-version: { type: string }
      base-version: { type: string }
    docker:
      - image: ocaml/opam2
    environment:
      CI: true
      TC_NATIVE_OCAML_SWITCH: << parameters.ocaml-version >>
      TC_BASE_VERSION: << parameters.base-version >>
    working_directory: ~/repo
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v2-native-dependencies-{{ .Branch }}-{{ checksum "tablecloth-native.opam" }}
            - v2-native-dependencies-{{ .Branch }}-
            - v2-native-dependencies-
      # m4 is a system dependency required by conf-m4 -> ocamlfind -> fmt -> alcotest
      - run: sudo apt-get install -y m4
      # See https://github.com/ocaml/opam-repository/issues/18711#issuecomment-843664632
      - run: git -C /home/opam/opam-repository pull origin master && opam update
      - run: make deps-native
      - run: make build-native
      - run: make test-native
      - run: make doc-native
      - run: make integration-test-native
      - save_cache:
          key: v2-native-dependencies-{{ .Branch }}-{{ checksum "tablecloth-native.opam" }}
          paths:
            - ~/.opam

  source-code-formatting:
    docker:
      - image: ocaml/opam2
    environment:
      CI: true
    working_directory: ~/repo
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v0-source-dependencies-ocamlformat-0.14
      # m4 is a system dependency required by conf-m4 -> ocamlfind -> fmt -> alcotest
      - run: sudo apt-get install -y m4
      - run: echo 'export PATH=/usr/lib/cargo/bin/fd:$PATH' >> ~/.bash_env
      # See https://github.com/ocaml/opam-repository/issues/18711#issuecomment-843664632
      - run: git -C /home/opam/opam-repository pull origin master && opam update
      - run: opam update && opam install ocamlformat reason -y
      - run: make check-format
      - save_cache:
          key: v0-source-dependencies-ocamlformat-0.14
          paths:
            - ~/.opam

  documentation-generator-build:
    docker:
      - image: ocaml/opam2:4.08
    environment:
      CI: true
    working_directory: ~/repo
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v2-native-dependencies-{{ .Branch }}-{{ checksum "tablecloth-native.opam" }}
            - v2-native-dependencies-{{ .Branch }}-
            - v2-native-dependencies-
      # m4 is a system dependency required lots of packages
      - run: sudo apt-get install -y m4
      # See https://github.com/ocaml/opam-repository/issues/18711#issuecomment-843664632
      - run: git -C /home/opam/opam-repository pull origin master && opam update
      - run: cd ocamldoc-json-generator && make deps
      - run: cd ocamldoc-json-generator && make doc
      # Check that model.json has been regenerated when there are changes in the interface files
      - run: git diff --exit-code website/model.json
      - save_cache:
          key: v2-native-dependencies-{{ .Branch }}-{{ checksum "tablecloth-native.opam" }}
          paths:
            - ~/.opam

  website-build:
    docker:
      - image: cimg/node:16.6.0
    environment:
      CI: true
      NODE_ENV: production
    working_directory: ~/repo/website
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v1-website-dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v1-website-dependencies-{{ .Branch }}-
            - v1-website-dependencies-
      - run: npm install
      - run: npm run build
      - save_cache:
          key: v1-website-dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/repo/website/node_modules

workflows:
  version: 2
  build:
    jobs:
      - rescript-build-and-test:
          matrix:
            parameters:
              rescript-version:
                - "9.1.4"
                # Pre version 6 not supported
      - native-build-and-test:
          matrix:
            parameters:
              # Contributions welcome for commented out versions, see README
              ocaml-version:
                 #- "4.06"
                 #- "4.07"
                 - "4.08"
                 - "4.09"
                 #- "4.10" # separate config below
                 #- "4.11" # no ocaml/opam2 version for this, probably works
              base-version:
                 #- "v0.9.4"
                 #- "v0.10.0"
                 #- "v0.11.1"
                 - "v0.12.2"
                 - "v0.13.2"
                 #- "v0.14.0"
      # Base 12 does not support OCaml 4.10
      - native-build-and-test:
          matrix:
            parameters:
              ocaml-version: ["4.10"]
              base-version: ["v0.13.2"]
      - source-code-formatting
      - documentation-generator-build
      - website-build
